
insert into public.quests (
  slug,
  title,
  kicker,
  description,
  why_it_matters,
  location_hint,
  duration_label,
  mood,
  accent,
  image_url,
  steps,
  journal_prompt,
  points_value
) values
(
  'sunrise-rhbfhbfghbrehgbf-place',
  'Watch sunrise from somewhere high',
  'Before the city starts',
  'Find a hill, bridge, rooftop cafe, college tower view or quiet overlook. Arrive before first light. Stay until the city has fully woken up.',
  'The point is not fitness or optimisation. It is the feeling of seeing somewhere familiar become strange again.',
  'A high place within 30 minutes',
  '60-90 min',
  'quiet',
  'gold',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85',
  array['Choose the place tonight, not tomorrow morning.', 'Bring coffee or something warm.', 'Take one photograph only after the sun has broken the horizon.', 'Write three lines about what felt different.'],
  'What did the city look like before it belonged to anyone else?',
  10
),
(
  'unknown-cafe',
  'Enter a cafe you have always walked past',
  'One unopened door',
  'Pick a cafe you have noticed but never entered. Order slowly. Sit without scrolling for at least twenty minutes.',
  'Small discoveries compound into a richer mental map of your own city.',
  'Somewhere familiar, but untried',
  '45 min',
  'curious',
  'forest',
  'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1600&q=85',
  array['Walk without checking reviews.', 'Ask what they recommend.', 'Notice one detail you would have missed from the street.', 'Save the receipt or photograph the table.'],
  'What did this place reveal once you were inside?',
  10
),
(
  'train-no-plan',
  'Take a train without planning the destination',
  'A deliberate detour',
  'Go to the station, pick a reachable stop that feels unfamiliar, and spend two hours there with no itinerary.',
  'Unplanned movement breaks the compression of routine. The memory comes from relinquishing certainty.',
  'A station within reach',
  'Half day',
  'wild',
  'navy',
  'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1600&q=85',
  array['Set a maximum travel budget.', 'Choose the platform before the destination.', 'Walk for twenty minutes before opening maps.', 'Find one object, view or conversation worth remembering.'],
  'What did you find because you refused to over-plan?',
  12
),
(
  'independent-cinema',
  'See a film at an independent cinema',
  'A room full of strangers',
  'Choose a film you would not normally stream. Arrive early enough to read the programme notes.',
  'The cinema turns passive watching into a place, a ritual and a shared atmosphere.',
  'Independent cinema or film society',
  'Evening',
  'social',
  'burgundy',
  'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&q=85',
  array['Invite one person whose taste differs from yours.', 'Do not watch the trailer first.', 'Stay through the credits.', 'Discuss the best image from the film afterwards.'],
  'Which frame stayed with you after leaving the building?',
  10
),
(
  'sketch-in-public',
  'Sketch something in public',
  'Look longer than usual',
  'Sit somewhere ordinary and draw a building, tree, table, person from memory or street corner. Quality is irrelevant. Attention is the point.',
  'Drawing slows perception. You leave with a memory made by attention, not consumption.',
  'Park, square, museum or cafe',
  '30 min',
  'creative',
  'orange',
  'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1600&q=85',
  array['Use paper, not a phone.', 'Pick one subject and stay with it.', 'Add the date and location to the page.', 'Photograph the sketch beside the scene.'],
  'What did drawing force you to notice?',
  8
)
on conflict (slug) do update set
  title = excluded.title,
  kicker = excluded.kicker,
  description = excluded.description,
  why_it_matters = excluded.why_it_matters,
  location_hint = excluded.location_hint,
  duration_label = excluded.duration_label,
  mood = excluded.mood,
  accent = excluded.accent,
  image_url = excluded.image_url,
  steps = excluded.steps,
  journal_prompt = excluded.journal_prompt,
  points_value = excluded.points_value,
  is_active = true,
  updated_at = now();
